---
title: "Dynamic HTML graph of Daily Temperatures"
author: "Jay M. Cooney"
date: "12/3/2020"
output: html_document
---

```{r, include = FALSE}
library(dplyr)
library(ggplot2)
library(ggmap)
library(htmlwidgets)
library(widgetframe)
library(tidyverse)
library(rnoaa)
library(xts)
library(dygraphs)
```


## Dynamic HTML graph of Daily Temperatures
```{r, echo = FALSE, message=FALSE, warning=FALSE}
#Completed with groupmates Bowei, Collin, Marko
#Download the daily weather data
d=meteo_tidy_ghcnd("USW00014733",
                   date_min = "2016-01-01", 
                   var = c("TMAX"),
                   keep_flags=T) %>% 
   mutate(date=as.Date(date),
          tmax=as.numeric(tmax)/10) #Divide the tmax data by 10 to convert to degrees.
#Convert d into an xts time series object 
tmax_time = xts(d$tmax, order.by = d$date)
#draw the plot, set the title of the dygraph
dygraph(tmax_time, main = "Daily Maximum Temperature in Buffalo, NY") %>%
  dySeries("V1", label = "Maximum Temperature") %>%
  dyRangeSelector(dateWindow = c("2020-01-01", "2020-10-31"))
```
