---
title: "Parallel Computing with R"
author: Jay Cooney
date: 11/19/2020
output: github_document
---


```{r, include = FALSE}
library(tidyverse)
library(spData)
library(sf)
library(mapview) 
library(foreach)
library(doParallel)
library(tidycensus)
registerDoParallel(4)
getDoParWorkers()
```

## Completed with groupmates Bowei, Collin, Marko
```{r, echo = FALSE, message=FALSE, warning=FALSE}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")
options(tigris_use_cache = TRUE)
#Download block-level data on population by race in each census block in Buffalo
erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE, 
                  summary_var = "P001001", cache_table=T) 
#Crop the county-level data
extent = c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)
erie_crop = st_crop(erie, extent)
#Write a foreach loop
erie_race = foreach(i = unique(erie_crop$variable), .combine=rbind) %do% {
  #generate random points for each person that resided within each polygon
  filter(erie_crop, variable == i) %>% st_sample(size=.$value) %>% 
    #convert the points to spatial features
    st_as_sf() %>% 
    #add a column named
    mutate(variable =i)
  }
mapview(erie_race, zcol = "variable", cex = 1, lwd = 0)
```